name: Release PR

on:
  pull_request:
  

jobs:
  process_release_pr:
    runs-on: ubuntu-latest
    if: ${{ github.base_ref == 'releases' || startsWith(github.base_ref, 'release/') }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: echo "Running here!"


  always_run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "SUCCESS!"
