name: Release PR
on: #[push]
  push:
    branches:
      - 'releases'
      - 'release/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - run: pip install -r requirements.txt

      - name: Create release
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          ./release.py
          