name: Release PR

on:
  pull_request:
  

jobs:
  process_release_pr:
    runs-on: ubuntu-latest
    if: > 
      ${{ 
        (github.base_ref == 'releases' || startsWith(github.base_ref, 'release/')) 
        && github.event.pull_request.base.repo.full_name == github.repository 
      }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: pip install -r CI/requirements.txt
      - name: Run release script
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: CI/release.py pr-action


  # Do we need this?
  # always_run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "SUCCESS!"
